photobooth/photobooth/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('wedding/', include('wedding.urls')),
    path('admin/', admin.site.urls),
]

photobooth/wedding/urls.py
from django.urls import path

from . import views

app_name = 'wedding'
urlpatterns = [
    path('', views.start, name='start'),
    path('ready/', views.ready, name='ready'),
    path('countdown/', views.countdown, name='countdown'),
    path('preview/', views.preview, name='preview'),
    path('collage/', views.collage, name='collage'),
    path('print/', views.print, name='print'),
    path('gallery/',views.gallery, name='gallery'),
]

photobooth/wedding/models.py
from django.db import models

# Create your models here.

class Collage(models.Model):
    collage_name = models.CharField(max_length=50)

class Picture(models.Model):
    collage = models.ForeignKey(Collage, on_delete=models.CASCADE)
    picture_name = models.CharField(max_length=50)
    picture_url = models.CharField(max_length=200)

photobooth/wedding/views.py
from django.shortcuts import render

from .models import Collage, Picture

import os
import time
import sys

folder_name = "test"
triggerCommand = "gphoto2 --capture-image-and-download"

nb_images = 1
listofimages = []

gallery_list = ['collage1',
#                'bild2',
#                'bild2',
#                'bild2',
#                'bild3',
#                'bild1',
#                'bild2',
#                'bild2',
#                'bild2',
#                'bild3',
#                'bild1',
#                'bild2',
#                'bild2',
#                'bild2',
#                'bild3',
#                'bild1',
#                'bild2',
#                'bild2',
#                'bild2',
#                'bild3',
                ]
for i in range(35):
    gallery_list.append('collage' + str(i+1))
Picture.objects.all().delete()
Collage.objects.all().delete()


c = Collage(collage_name = "test_collage")
c.save()
for i in range(len(gallery_list)):
    c.picture_set.create(picture_name = gallery_list[i],
                        picture_url = gallery_list[i])

def start(request):
    os.system("mkdir " + str(folder_name))

    global nb_images
    nb_images = 0

    return render(request, 'wedding/start.html')

def ready(request):

    global nb_images
    if nb_images < 4:
        return render(request, 'wedding/ready.html')
    else:
        nb_images = 0
        sys.stdout.write("Collage wird erstellt!\n")
        return render(request, 'wedding/ready.html')

def countdown(request):
    return render(request, 'wedding/countdown.html')

def preview(request):

    #os.system(triggerCommand)
    #time.sleep(1)

    global nb_images
    nb_images += 1

    sys.stdout.write("Bild " + str(nb_images) +  " wurde geschossen\n")

    global c
    c.picture_set.create(picture_name = "bild" + str(nb_images),
                         picture_url = "bild" + str(nb_images))
    return render(request, 'wedding/preview.html')

def collage(request):
    return render(request, 'wedding/collage.html')

def print(request):
    return render(request, 'wedding/print.html')

def gallery(request):

    gallery_list = Collage.objects.first()

    return render(request, 'wedding/gallery.html', {"gallery_list" : gallery_list})

photobooth/wedding/templates/wedding/countdown.html
{% load static %}
<html>
<link rel="stylesheet" type="text/css" href="{% static 'wedding/countdown.css' %}">

<body onload="countdown()">
<div class="background">
    <p id="countdown-number"> </p>
</div>

<form action="{% url 'wedding:preview' %}" method="post">
  {% csrf_token %}
  <button class="preview" id="preview" style="display: none;">
</form>
</body>

</html>



<!-- JavaScript part for the button -->
<script type="text/javascript">

  var seconds = 6; // Total seconds to wait

  function countdown() {
    seconds = seconds - 1; // Deswegen 6 sec
    if (seconds < 1) {
       seconds = 6;
       document.getElementById("countdown-number").innerHTML = "Lächeln!!!";
        // After countdown
        // TODO: Capture image function
        document.getElementById("preview").click();

    } else {
        // Update button value
        document.getElementById("countdown-number").innerHTML = seconds;
        // Count down using javascript
        window.setTimeout("countdown()", 1000);
    }
  }
</script>

photobooth/wedding/templates/wedding/gallery.html
{% load static %}
{% get_static_prefix as STATIC_URL %}
<style>
	@font-face { font-family: 'Tangerine';
             src: url("{% static 'wedding/fonts/Tangerine/Tangerine-Regular.ttf' %}"); }
</style>

<html lang="en">
	<head>
	<meta charset="utf-8" />
    <link rel="stylesheet" type="text/css" href="{% static 'wedding/gallery.css' %}" media="screen">
	</head>
  
	<body>

	<div class="textbox">
	<h1>
		Photobooth gallery
	</h1>
	</div>


 		<div class="gallery" id="gallery">
        {% for pic in gallery_list.picture_set.all %}
				 <div class="gallery-item">
					<div class="content"><img src="{{STATIC_URL}}wedding/collage_example/{{pic.picture_name}}.jpg" alt=""></div>
				</div>
        {% endfor %}
		</div>

	</body>
</html>

<script type="text/javascript">

var gallery = document.querySelector('#gallery');
var getVal = function (elem, style) { return parseInt(window.getComputedStyle(elem).getPropertyValue(style)); };
var getHeight = function (item) { return item.querySelector('.content').getBoundingClientRect().height; };
var resizeAll = function () {
    var altura = getVal(gallery, 'grid-auto-rows');
    var gap = getVal(gallery, 'grid-row-gap');
    gallery.querySelectorAll('.gallery-item').forEach(function (item) {
        var el = item;
        el.style.gridRowEnd = "span " + Math.ceil((getHeight(item) + gap) / (altura + gap));
    });
};
gallery.querySelectorAll('img').forEach(function (item) {
    item.classList.add('byebye');
    if (item.complete) {
        console.log(item.src);
    }
    else {
        item.addEventListener('load', function () {
            var altura = getVal(gallery, 'grid-auto-rows');
            var gap = getVal(gallery, 'grid-row-gap');
            var gitem = item.parentElement.parentElement;
            gitem.style.gridRowEnd = "span " + Math.ceil((getHeight(gitem) + gap) / (altura + gap));
            item.classList.remove('byebye');
        });
    }
});
window.addEventListener('resize', resizeAll);
gallery.querySelectorAll('.gallery-item').forEach(function (item) {
    item.addEventListener('click', function () {
        item.classList.toggle('full');
    });
});

</script>

photobooth/wedding/templates/wedding/preview.html
{% load static %}
<html>
<link rel="stylesheet" type="text/css" href="{% static 'wedding/style.css' %}">

<div class="background">
  <h2>Bild preview.</h2>
  <form action="{% url 'wedding:ready' %}" method="post">
    {% csrf_token %}
    <button class="btn">Nächstes Bild</button>
  </form>

</div>

</html>

photobooth/wedding/templates/wedding/ready.html
{% load static %}
<html>
<link rel="stylesheet" type="text/css" href="{% static 'wedding/style.css' %}">

<div class="background">
  <h1>Bild Nummer 4:</h1>

  <form action="{% url 'wedding:countdown' %}" method="post">
    {% csrf_token %}
    <button class="btn">Foto schießen!</button>
  </form>

</div>

</html>

photobooth/wedding/templates/wedding/start.html
{% load static %}
<html>
<link rel="stylesheet" type="text/css" href="{% static 'wedding/style.css' %}">

<div class="background">
  <h2>Es werden vier Bilder nacheinander gemacht <br>
  und dann wird eine Collage erstellt.</h2>
  <form action="{% url 'wedding:ready' %}" method="post">
    {% csrf_token %}
    <button class="btn">Start</button>
  </form>

</div>

</html>